"""add creator_project + equipment process_params worker_count

Revision ID: 2de9e77c0322
Revises: 5ca88a91a09e
Create Date: 2026-05-11 15:47:03.854862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2de9e77c0322'
down_revision: Union[str, None] = '5ca88a91a09e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('md_creator_project',
    sa.Column('creator_project_id', sa.String(length=36), nullable=False),
    sa.Column('project_name', sa.String(length=200), nullable=False),
    sa.Column('project_version', sa.String(length=50), nullable=True),
    sa.Column('project_status', sa.String(length=20), nullable=False),
    sa.Column('factory_id', sa.String(length=36), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('creator_url', sa.String(length=500), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['factory_id'], ['md_factory.factory_id'], ),
    sa.PrimaryKeyConstraint('creator_project_id')
    )
    op.add_column('md_equipment_process_parameters', sa.Column('standard_worker_count', sa.Integer(), nullable=True))
    op.add_column('sim_simulation_plan', sa.Column('creator_project_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'sim_simulation_plan', 'md_creator_project', ['creator_project_id'], ['creator_project_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sim_simulation_plan', type_='foreignkey')
    op.drop_column('sim_simulation_plan', 'creator_project_id')
    op.drop_column('md_equipment_process_parameters', 'standard_worker_count')
    op.drop_table('md_creator_project')
    # ### end Alembic commands ###
