"""add md_stage_transition

Revision ID: 3e93387da26b
Revises: 7fcc7e56782b
Create Date: 2026-04-24 16:39:54.600380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e93387da26b'
down_revision: Union[str, None] = '7fcc7e56782b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('md_stage_transition',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('from_stage_id', sa.String(length=36), nullable=False),
    sa.Column('to_stage_id', sa.String(length=36), nullable=False),
    sa.Column('connection_type', sa.String(length=10), nullable=False),
    sa.Column('connection_time', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("connection_type IN ('S2S', 'E2S')", name='ck_stage_transition_connection_type'),
    sa.ForeignKeyConstraint(['from_stage_id'], ['md_stage.stage_id'], ),
    sa.ForeignKeyConstraint(['to_stage_id'], ['md_stage.stage_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_stage_id', 'to_stage_id', name='uq_stage_transition_pair')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('md_stage_transition')
    # ### end Alembic commands ###
