"""add ignore_wo to plan

Revision ID: 4d98ddce63cf
Revises: 3e93387da26b
Create Date: 2026-04-25 11:22:35.223214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d98ddce63cf'
down_revision: Union[str, None] = '3e93387da26b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'sim_simulation_plan',
        sa.Column('ignore_wo', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sim_simulation_plan', 'ignore_wo')
    # ### end Alembic commands ###
