"""equipment per-line + 5 child tables

Revision ID: 6de3ebe1dca5
Revises: 4d98ddce63cf
Create Date: 2026-04-25 14:55:23.737688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6de3ebe1dca5'
down_revision: Union[str, None] = '4d98ddce63cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('md_equipment_bom_part',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('equipment_id', sa.String(length=36), nullable=False),
    sa.Column('part_code', sa.String(length=50), nullable=False),
    sa.Column('part_name', sa.String(length=200), nullable=False),
    sa.Column('part_model', sa.String(length=200), nullable=False),
    sa.Column('part_manufacturer', sa.String(length=200), nullable=False),
    sa.Column('part_qty', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('parent_part_id', sa.String(length=36), nullable=False),
    sa.Column('part_position', sa.String(length=200), nullable=True),
    sa.Column('part_photo_url', sa.String(length=200), nullable=True),
    sa.Column('part_theoretical_life', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('part_remaining_life', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['md_equipment.equipment_id'], ),
    sa.ForeignKeyConstraint(['parent_part_id'], ['md_equipment_bom_part.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('md_equipment_operation_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('equipment_id', sa.String(length=36), nullable=False),
    sa.Column('record_code', sa.String(length=36), nullable=False),
    sa.Column('record_type', sa.String(length=36), nullable=False),
    sa.Column('related_department', sa.String(length=36), nullable=True),
    sa.Column('stage_status', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['md_equipment.equipment_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('md_equipment_process_parameters',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('equipment_id', sa.String(length=36), nullable=False),
    sa.Column('standard_ct', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('standard_yield_rate', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('standard_work_efficiency', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['md_equipment.equipment_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('equipment_id')
    )
    op.create_table('md_equipment_sop',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('equipment_id', sa.String(length=36), nullable=False),
    sa.Column('document_no', sa.String(length=50), nullable=False),
    sa.Column('document_title', sa.String(length=200), nullable=False),
    sa.Column('document_version', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['md_equipment.equipment_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('md_equipment_technical_specification',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('equipment_id', sa.String(length=36), nullable=False),
    sa.Column('main_parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('power', sa.String(length=36), nullable=True),
    sa.Column('size', sa.String(length=36), nullable=True),
    sa.Column('weight', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['md_equipment.equipment_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('equipment_id')
    )
    op.add_column('md_equipment', sa.Column('line_id', sa.String(length=36), nullable=False))
    op.add_column('md_equipment', sa.Column('equipment_group_id', sa.String(length=50), nullable=True))
    op.add_column('md_equipment', sa.Column('brand', sa.String(length=200), nullable=True))
    op.add_column('md_equipment', sa.Column('manufacture_date', sa.DateTime(), nullable=True))
    op.add_column('md_equipment', sa.Column('manufacture_code', sa.String(length=50), nullable=True))
    op.add_column('md_equipment', sa.Column('made_in', sa.String(length=50), nullable=True))
    op.add_column('md_equipment', sa.Column('supplier', sa.String(length=50), nullable=True))
    op.add_column('md_equipment', sa.Column('supplier_phone', sa.String(length=50), nullable=True))
    op.add_column('md_equipment', sa.Column('purchase_date', sa.DateTime(), nullable=True))
    op.add_column('md_equipment', sa.Column('service_life', sa.Integer(), nullable=True))
    op.add_column('md_equipment', sa.Column('unit', sa.String(length=20), nullable=True))
    op.add_column('md_equipment', sa.Column('location', sa.String(length=50), nullable=True))
    op.add_column('md_equipment', sa.Column('equipment_photo', sa.String(length=500), nullable=True))
    op.add_column('md_equipment', sa.Column('responsible_person', sa.String(length=50), nullable=True))
    op.add_column('md_equipment', sa.Column('asset_code', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'md_equipment', 'md_production_line', ['line_id'], ['line_id'])
    op.drop_column('md_equipment', 'standard_ct')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('md_equipment', sa.Column('standard_ct', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'md_equipment', type_='foreignkey')
    op.drop_column('md_equipment', 'asset_code')
    op.drop_column('md_equipment', 'responsible_person')
    op.drop_column('md_equipment', 'equipment_photo')
    op.drop_column('md_equipment', 'location')
    op.drop_column('md_equipment', 'unit')
    op.drop_column('md_equipment', 'service_life')
    op.drop_column('md_equipment', 'purchase_date')
    op.drop_column('md_equipment', 'supplier_phone')
    op.drop_column('md_equipment', 'supplier')
    op.drop_column('md_equipment', 'made_in')
    op.drop_column('md_equipment', 'manufacture_code')
    op.drop_column('md_equipment', 'manufacture_date')
    op.drop_column('md_equipment', 'brand')
    op.drop_column('md_equipment', 'equipment_group_id')
    op.drop_column('md_equipment', 'line_id')
    op.drop_table('md_equipment_technical_specification')
    op.drop_table('md_equipment_sop')
    op.drop_table('md_equipment_process_parameters')
    op.drop_table('md_equipment_operation_records')
    op.drop_table('md_equipment_bom_part')
    # ### end Alembic commands ###
