"""add res_simulation_event

Revision ID: e63fd69f938e
Revises: 6de3ebe1dca5
Create Date: 2026-04-25 17:28:25.903603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e63fd69f938e'
down_revision: Union[str, None] = '6de3ebe1dca5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('res_simulation_event',
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('result_id', sa.String(length=36), nullable=False),
    sa.Column('timestamp_ms', sa.BigInteger(), nullable=False),
    sa.Column('equipment_id', sa.String(length=36), nullable=True),
    sa.Column('prim_path', sa.String(length=200), nullable=True),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('product_id', sa.String(length=80), nullable=True),
    sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['result_id'], ['res_simulation_result.result_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('ix_sim_event_result_eq_ts', 'res_simulation_event', ['result_id', 'equipment_id', 'timestamp_ms'], unique=False)
    op.create_index('ix_sim_event_result_product', 'res_simulation_event', ['result_id', 'product_id'], unique=False)
    op.create_index('ix_sim_event_result_ts', 'res_simulation_event', ['result_id', 'timestamp_ms'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sim_event_result_ts', table_name='res_simulation_event')
    op.drop_index('ix_sim_event_result_product', table_name='res_simulation_event')
    op.drop_index('ix_sim_event_result_eq_ts', table_name='res_simulation_event')
    op.drop_table('res_simulation_event')
    # ### end Alembic commands ###
